import streamlit as st
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
import textstat
import re

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="AI vs Human Text Detector",
    page_icon="🤖",
    layout="centered"
)

# ── Header ────────────────────────────────────────────────────────────────────
st.title("🤖 AI vs Human Text Detector")
st.markdown(
    "Paste any text below to detect whether it was written by a **human** "
    "or generated by an **AI** (GPT, Claude, Gemini, etc.)"
)
st.divider()

# ── Feature extraction ────────────────────────────────────────────────────────
def extract_linguistic_features(text):
    """Extract interpretable linguistic fingerprint features."""
    words = text.split()
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 0]

    features = {
        "word_count": len(words),
        "avg_word_length": np.mean([len(w) for w in words]) if words else 0,
        "sentence_count": len(sentences),
        "avg_sentence_length": np.mean([len(s.split()) for s in sentences]) if sentences else 0,
        "lexical_diversity": len(set(words)) / len(words) if words else 0,
        "flesch_score": textstat.flesch_reading_ease(text),
        "flesch_kincaid_grade": textstat.flesch_kincaid_grade(text),
        "punctuation_density": len(re.findall(r'[,;:—]', text)) / len(words) if words else 0,
        "question_marks": text.count('?'),
        "exclamation_marks": text.count('!'),
        "unique_word_ratio": len(set(w.lower() for w in words)) / len(words) if words else 0,
    }
    return features

def analyse_text(text):
    """
    Heuristic classifier based on linguistic fingerprints.
    In a full version this would use a trained ML model.
    """
    if len(text.split()) < 10:
        return None, None, None

    features = extract_linguistic_features(text)

    # Scoring heuristics based on known AI vs human patterns
    ai_score = 0.5  # start neutral

    # AI text tends to have very consistent sentence lengths
    sentence_len_variance = features["avg_sentence_length"]
    if 15 <= sentence_len_variance <= 25:
        ai_score += 0.08

    # AI text tends to have higher average word length (more formal)
    if features["avg_word_length"] > 5.2:
        ai_score += 0.06

    # Lower lexical diversity often indicates AI
    if features["lexical_diversity"] < 0.6:
        ai_score += 0.07

    # Very high Flesch score (too readable) can indicate AI
    if 60 <= features["flesch_score"] <= 75:
        ai_score += 0.05

    # Human text tends to use more punctuation variety
    if features["punctuation_density"] < 0.02:
        ai_score += 0.05

    # Humans use more questions and exclamations
    if features["question_marks"] == 0 and features["exclamation_marks"] == 0:
        ai_score += 0.06

    # Cap between 0 and 1
    ai_score = max(0.05, min(0.95, ai_score))
    human_score = 1 - ai_score

    label = "AI Generated" if ai_score > 0.5 else "Human Written"
    return label, ai_score, human_score, features


# ── UI ─────────────────────────────────────────────────────────────────────────
sample_ai = """Artificial intelligence represents a transformative paradigm shift in the 
way humans interact with technology. By leveraging sophisticated algorithms and 
neural network architectures, modern AI systems demonstrate remarkable capabilities 
in natural language understanding, pattern recognition, and complex problem-solving. 
These advancements have profound implications for industries ranging from healthcare 
to financial services."""

sample_human = """I've been thinking about AI a lot lately and honestly it's kind of wild 
how fast things are moving. Like, last year I couldn't have imagined having a conversation 
with a chatbot that actually makes sense? My friend showed me this thing the other day and 
I just couldn't tell if it was real or not. Bit scary tbh but also kind of exciting I guess."""

col1, col2 = st.columns(2)
with col1:
    if st.button("📋 Try AI sample", use_container_width=True):
        st.session_state["input_text"] = sample_ai
with col2:
    if st.button("✍️ Try human sample", use_container_width=True):
        st.session_state["input_text"] = sample_human

user_text = st.text_area(
    "Paste your text here:",
    value=st.session_state.get("input_text", ""),
    height=200,
    placeholder="Enter at least 10 words...",
    key="text_input"
)

if st.button("🔍 Analyse Text", type="primary", use_container_width=True):
    if not user_text or len(user_text.split()) < 10:
        st.warning("Please enter at least 10 words for a reliable analysis.")
    else:
        result = analyse_text(user_text)
        label, ai_score, human_score, features = result

        st.divider()

        # ── Result ──
        if label == "AI Generated":
            st.error(f"🤖 **{label}** — {ai_score*100:.0f}% confidence")
        else:
            st.success(f"✍️ **{label}** — {human_score*100:.0f}% confidence")

        # ── Confidence bar ──
        st.markdown("**Confidence breakdown:**")
        conf_df = pd.DataFrame({
            "Label": ["AI Generated", "Human Written"],
            "Confidence": [round(ai_score * 100, 1), round(human_score * 100, 1)]
        })
        st.bar_chart(conf_df.set_index("Label"))

        # ── Linguistic features ──
        st.divider()
        st.subheader("📊 Linguistic Fingerprint Analysis")
        st.caption("These features are used to distinguish AI from human writing patterns.")

        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Word count", features["word_count"])
            st.metric("Sentence count", features["sentence_count"])
            st.metric("Avg word length", f"{features['avg_word_length']:.2f}")
        with col2:
            st.metric("Lexical diversity", f"{features['lexical_diversity']:.2f}",
                      help="Ratio of unique words. Lower = more repetitive (AI signal)")
            st.metric("Flesch reading ease", f"{features['flesch_score']:.1f}",
                      help="Higher = more readable. AI tends to cluster around 60-75")
            st.metric("Avg sentence length", f"{features['avg_sentence_length']:.1f}")
        with col3:
            st.metric("Punctuation density", f"{features['punctuation_density']:.3f}")
            st.metric("Questions (?)", features["question_marks"])
            st.metric("Exclamations (!)", features["exclamation_marks"])

        # ── Key signals ──
        st.divider()
        st.subheader("🔍 Key Signals Detected")

        signals = []
        if features["lexical_diversity"] < 0.6:
            signals.append(("⚠️ Low lexical diversity", "AI text often reuses similar vocabulary patterns", "warning"))
        else:
            signals.append(("✅ High lexical diversity", "Varied vocabulary — consistent with human writing", "success"))

        if features["question_marks"] == 0 and features["exclamation_marks"] == 0:
            signals.append(("⚠️ No questions or exclamations", "Human writing typically shows more emotional punctuation", "warning"))
        else:
            signals.append(("✅ Emotional punctuation present", "Questions/exclamations detected — human signal", "success"))

        if 60 <= features["flesch_score"] <= 75:
            signals.append(("⚠️ Flesch score in AI range", "Reading ease between 60-75 is common in AI-generated text", "warning"))

        for signal_text, desc, signal_type in signals:
            if signal_type == "warning":
                st.warning(f"**{signal_text}** — {desc}")
            else:
                st.success(f"**{signal_text}** — {desc}")

st.divider()
st.caption(
    "Built by [Omkar Salekar](https://linkedin.com/in/omkar-salekar-23188026b) · "
    "MSc Data Science & AI, Oxford Brookes · "
    "[GitHub](https://github.com/omiiii274/LLM-vs-Human-Text-Classifier)"
)
